### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/College-Space#1]
Want a clean and attractive Readme file

**Comment by foxieze** [comment]
I can work on this - anything specific you want in the README.md? Do you want a Hacktoberfest image? Any build passing / failing images?

**Comment by Gautam-Arora24** [comment]
ya.. Go Ahead. You can add images from the live website.

**Comment by Gautam-Arora24** [comment]
Also you can add Tech Stack, Running locally section etc.

**Comment by kjvjobin** [comment]
Please assign me this issue

**Comment by Gautam-Arora24** [comment]
Go Ahead @jobinkeecheril

**Comment by davies-jack** [comment]
if nothing ends up being done with this I'm happy to do it

**Comment by Gautam-Arora24** [comment]
I appreciate your kindness @jackethdavies . Kindly star this repo so that you get updates regarding the repo

**Comment by Gautam-Arora24** [comment]
@jackethdavies If you want you can add some more details about the project like how to clone and run on local system. Also you can add some screenshots of the live web app.

**Comment by davies-jack** [comment]
Sure thing. Will get to work on it.

**Comment by Gautam-Arora24** [comment]
@jackethdavies Ping me here if any help is needed

**Comment by davies-jack** [comment]
Hi @Gautam-Arora24 - What keys do you have in your .env file? I assume you use this to put your database connection string into etc. I will add a blank `.env.example` file alongside the README instructions to make it easier for people

**Comment by Gautam-Arora24** [comment]
Yes @jackethdavies . I have used Database connection String.

**Comment by davies-jack** [comment]
Ok thanks. I have added a pull request for you to take a look at @Gautam-Arora24

**Comment by Gautam-Arora24** [comment]
Great Work @jackethdavies
